### ISSUE TITLE
Clean up MessageSimulatorJFrame.java

### ISSUE THREAD

**Issue by garys-esri** [Esri/vehicle-commander#16]
https://github.com/Esri/vehicle-commander/blob/master/source/MessageSimulator/src/com/esri/messagesimulator/MessageSimulatorJFrame.java

1. Use Logger instead of System.out.
2. Capitalize private class names for better readability.

**Comment by csmoore** [comment]
Just checking (&sorry in advanced for my confusion) - was this assigned to me to verify?  

I thought I was just verifying but noticed the `System.out`'s were still there.

**Comment by garys-esri** [comment]
Ay ay ay...I had one job to do...

I'll remove the `System.out`s.

**Comment by garys-esri** [comment]
Done in 264c9810b4a7e736cf7b30d1a4a304e00c2930f2 , which is part of pull request #48.

**Comment by csmoore** [comment]
Verified
