### ISSUE TITLE
Switch between MGRS and lon/lat

### ISSUE THREAD

**Issue by garys-esri** [Esri/vehicle-commander#24]
Add a setting for switching between MGRS display and longitude/latitude display.

**Comment by garys-esri** [comment]
This behavior is in f30c68428dddad408fcd0c6bf2172a78341b39fd . To use it, go to Main Menu > Options > Settings. There you can change between MGRS and lon/lat.

**Comment by garys-esri** [comment]
Assigning this issue and others to @csmoore to test and merge.

**Comment by csmoore** [comment]
Verified

![image](https://cloud.githubusercontent.com/assets/3090809/6332590/77519f06-bb54-11e4-9e6b-3bea3bfc823a.png)

![image](https://cloud.githubusercontent.com/assets/3090809/6332602/83f0be7c-bb54-11e4-81a5-9a19b905521d.png)


I wonder if this setting should eventually change the overlay grid shown as well (from MGRS grid to Lat/Lon)?

**Comment by garys-esri** [comment]
Good question. I just created #50.
