### ISSUE TITLE
Simplify version.xml

### ISSUE THREAD

**Issue by ACueva** [Esri/vehicle-commander#42]
Currently script sets the following variables:
 ${dir.agsruntimejavasdk}" 
 ${version.runtime}" 

Update current script to only set these two variables without figuring out install location.

https://github.com/Esri/vehicle-commander/blob/master/source/VehicleCommander/versions.xml

We will now update the version number using v.next branch.

**Comment by csmoore** [comment]
Assigning to @garys-esri to verify (rather than Avi since he already has this project set up)

**Comment by garys-esri** [comment]
Thanks. I'll have time to check it this afternoon.

**Comment by garys-esri** [comment]
Oops, I still need to check #54.

**Comment by garys-esri** [comment]
Fixed in #53 and #54
